services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main

  backend:
    image: khuzzyatov/miroro_backend:latest
    container_name: backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/uploads
    networks:
      - main

  frontend:
    image: khuzzyatov/miroro_frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - main

volumes:
  pgdata:

networks:
  main:
    driver: bridge