spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.xml

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  upload:
    img-path: uploads/img

cdek:
  auth:
    url: https://api.cdek.ru/v2
    client-id: ${CDEK_CLIENT_ID}
    client-secret: ${CDEK_CLIENT_SECRET}
    country-code: RU

logging:
  structured:
    format:
      console: ecs